export const INLINE_MARRIAGE_MAX_CENTER_Y_DELTA = 28
export const INLINE_MARRIAGE_MAX_GAP_FACTOR = 0.8

export const SPOUSE_PROJECTION_NODE_WIDTH = 152
export const SPOUSE_PROJECTION_NODE_HEIGHT = 54
export const SPOUSE_PROJECTION_HORIZONTAL_GAP = 28
export const SPOUSE_PROJECTION_VERTICAL_ANCHOR_OFFSET = 6
export const SPOUSE_PROJECTION_VERTICAL_STEP_GAP = 18
export const SPOUSE_PROJECTION_FALLBACK_COLLISION_PADDING = 10
export const SPOUSE_PROJECTION_SAME_ROW_COLLISION_PADDING = 96
