# LegendariumExplorer - HTML Editor Data Generator
# Generates static data.js from JSON datasets for the HTML editor

param(
    [string]$DatasetName = "demo",
    [switch]$Verbose
)

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
$DatasetsPath = Join-Path $RepoRoot "datasets"
$HtmlEditorPath = Join-Path $RepoRoot "HTMLEditor"
$OutputFile = Join-Path $HtmlEditorPath "data.js"

Write-Host "=================================================="
Write-Host "LegendariumExplorer - HTML Editor Data Generator"
Write-Host "=================================================="
Write-Host "Dataset: $DatasetName"
Write-Host "Output:  $OutputFile"
Write-Host ""

# Validate dataset exists
$DatasetPath = Join-Path $DatasetsPath $DatasetName
if (-not (Test-Path $DatasetPath)) {
    Write-Error "Dataset '$DatasetName' not found at $DatasetPath"
    exit 1
}

$PersonsPath = Join-Path $DatasetPath "persons"
$RelationsPath = Join-Path $DatasetPath "relations"

# Load all persons
Write-Host "Loading persons..."
$PersonsFiles = Get-ChildItem -Path $PersonsPath -Filter "*.json" -File
$PersonsData = @()

foreach ($file in $PersonsFiles) {
    if ($file.Name -eq "index.json") { continue }
    
    try {
        $content = Get-Content -Path $file.FullName -Raw -Encoding UTF8
        $person = $content | ConvertFrom-Json
        $PersonsData += $person
        
        if ($Verbose) {
            Write-Host "  ✓ $($person.name) ($($person.id))"
        }
    }
    catch {
        Write-Warning "Failed to parse $($file.Name): $_"
    }
}

Write-Host "  Loaded $($PersonsData.Count) persons"

# Load all relations
Write-Host "Loading relations..."
$RelationsFiles = Get-ChildItem -Path $RelationsPath -Filter "*.json" -File
$RelationsData = @()

foreach ($file in $RelationsFiles) {
    if ($file.Name -eq "index.json") { continue }
    
    try {
        $content = Get-Content -Path $file.FullName -Raw -Encoding UTF8
        $relation = $content | ConvertFrom-Json
        $RelationsData += $relation
        
        if ($Verbose) {
            Write-Host "  ✓ $($relation.type): $($relation.from) -> $($relation.to)"
        }
    }
    catch {
        Write-Warning "Failed to parse $($file.Name): $_"
    }
}

Write-Host "  Loaded $($RelationsData.Count) relations"
Write-Host ""

# Generate data.js
Write-Host "Generating data.js..."

$PersonsJson = $PersonsData | ConvertTo-Json -Depth 10 -Compress:$false
$RelationsJson = $RelationsData | ConvertTo-Json -Depth 10 -Compress:$false

# Get list of all datasets
$AllDatasets = @()
Get-ChildItem -Path $DatasetsPath -Directory | ForEach-Object {
    $AllDatasets += $_.Name
}

$AllDatasetsJson = $AllDatasets | ConvertTo-Json -Compress:$false

$DataJsContent = @"
// Auto-generated multi-dataset data for client-side editor
// Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
// Datasets: $($AllDatasets -join ", ")
// DO NOT EDIT - This file is auto-generated by Update-HtmlEditorData.ps1

const AVAILABLE_DATASETS = $AllDatasetsJson;

const ALL_DATASETS_DATA = {
  '$DatasetName': {
    persons: $PersonsJson,
    relations: $RelationsJson
  }
};

const PERSONS_DATA = ALL_DATASETS_DATA['$DatasetName'].persons;
const RELATIONS_DATA = ALL_DATASETS_DATA['$DatasetName'].relations;
const CURRENT_DATASET = '$DatasetName';
"@

# Write output file
Set-Content -Path $OutputFile -Value $DataJsContent -Encoding UTF8

Write-Host ""
Write-Host "==================================================" -ForegroundColor Green
Write-Host "✅ SUCCESS!" -ForegroundColor Green
Write-Host "=================================================="
Write-Host "Generated: $OutputFile"
Write-Host "Persons:   $($PersonsData.Count)"
Write-Host "Relations: $($RelationsData.Count)"
Write-Host ""
Write-Host "Open in browser:"
Write-Host "  file:///$($OutputFile -replace '\\', '/' -replace '^C:', 'C:')"
Write-Host ""
